### ISSUE TITLE
Hacker earth-1 

### ISSUE THREAD

**Issue by skchinna7** [akashraj001/cloudyML#1]
Your code has the error i think you should figure it out nothing works fine may be try to rewrite the code and make it work because I think so

**Comment by akashraj001** [comment]
Maybe you have not extracted the files from the hackerearth(https://www.hackerearth.com/challenges/competitive/hackerearth-deep-learning-challenge-identify-dance-form/) website as i have mentioned in youtube video:https://youtu.be/uyK8esXJWv0 . After extracing point to that directory. Then everything should work fine. Still if the error is there please let me know the line where the error happened and the error message. Then i may help you better.
