### ISSUE TITLE
Training works fine but there is issue in making prediction and creating test_generator with Imagedatagenerator.

### ISSUE THREAD

**Issue by Akshayvasav** [akashraj001/cloudyML#2]
![Error_dance_classification](https://user-images.githubusercontent.com/50213973/89724804-4be27980-da25-11ea-9977-b3c03c4ed401.JPG)

**Comment by akashraj001** [comment]
Inside the test folder make a "New Folder" and then cut paste all the images(in the "test" folder) to the "New Folder".
After that run this code. It should run fine.

**Comment by Akshayvasav** [comment]
Thank you for your prompt response.
I did the same now image data generation is working fine.
But now got issue in prediction. 
Just clear this doubt your code will rock as it is optimized one.
![Dance_prediction_error](https://user-images.githubusercontent.com/50213973/89731169-91716780-da62-11ea-8b1d-99a20e168129.JPG)

**Comment by akashraj001** [comment]
Can you show the value inside the predict_class_indices

**Comment by Akshayvasav** [comment]
![Predicted_class_indices](https://user-images.githubusercontent.com/50213973/89734141-e2d82180-da77-11ea-9ab0-cfcc84843ba2.JPG)

**Comment by akashraj001** [comment]
predicted_class_indices=np.argmax(pred,axis=1)
 You need to give the parameter as "axis=1"

**Comment by Akshayvasav** [comment]
Yesssss... now it's working fine.
I am able to predict dance classes now.
Just one out of scope question. Do you know how to extract features of a single image with Imagedatagenerator and pass it to model for prediction on single image?

**Comment by akashraj001** [comment]
With Imagedatagenerator we dont do feature extraction. We just make a pipeline for inputing our image data.
If you want to make prediction for  a single image then you need to put that single image alone in the "New Folder"  I mentioned in above comments

**Comment by Akshayvasav** [comment]
Yes, I am able to do that after placing only a single image in the "New folder".
But any alternative way that I can predict a single image by providing a customized paths of the image every time.
